#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const project=path.resolve(process.argv[2]||'');
if(!project)throw new Error('Quest Bubblewrap project path is required.');
const manifestPath=path.join(project,'app/src/main/AndroidManifest.xml');
let manifest=fs.readFileSync(manifestPath,'utf8');
const marker='android:name=".XRBridgeActivity"';
if(!manifest.includes(marker)){
  const activity=`\n        <activity\n            android:name=".XRBridgeActivity"\n            android:exported="true"\n            android:excludeFromRecents="true"\n            android:noHistory="true"\n            android:theme="@android:style/Theme.Translucent.NoTitleBar">\n            <intent-filter>\n                <action android:name="android.intent.action.VIEW" />\n                <category android:name="android.intent.category.DEFAULT" />\n                <category android:name="android.intent.category.BROWSABLE" />\n                <data android:scheme="rantlistxr" android:host="open" />\n            </intent-filter>\n        </activity>\n`;
  if(!manifest.includes('</application>'))throw new Error('Generated Android manifest has no application closing tag.');
  manifest=manifest.replace('</application>',activity+'    </application>');
  fs.writeFileSync(manifestPath,manifest);
}
const javaDir=path.join(project,'app/src/main/java/fun/workwork/rantlist');fs.mkdirSync(javaDir,{recursive:true});
fs.writeFileSync(path.join(javaDir,'XRBridgeActivity.java'),`package fun.workwork.rantlist;\n\nimport android.app.Activity;\nimport android.content.ActivityNotFoundException;\nimport android.content.Intent;\nimport android.net.Uri;\nimport android.os.Bundle;\n\npublic final class XRBridgeActivity extends Activity {\n  private static final String QUEST_BROWSER = "com.oculus.browser";\n  private static final String QUEST_XR_ACTIVITY = "com.oculus.browser.WebXRCustomTabActivity";\n  private static final String DEFAULT_URL = "https://rantlist.me/stage/?rantlistImmersive=1";\n\n  @Override protected void onCreate(Bundle state) { super.onCreate(state); launch(getIntent()); }\n  @Override protected void onNewIntent(Intent intent) { super.onNewIntent(intent); setIntent(intent); launch(intent); }\n\n  private void launch(Intent source) {\n    Uri target = validatedTarget(source == null ? null : source.getData());\n    if (target == null) { finish(); return; }\n    Intent xr = new Intent(Intent.ACTION_VIEW, target);\n    xr.setClassName(QUEST_BROWSER, QUEST_XR_ACTIVITY);\n    xr.addCategory(Intent.CATEGORY_BROWSABLE);\n    xr.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP);\n    try { startActivity(xr); } catch (ActivityNotFoundException missing) {\n      Intent legacy = new Intent(Intent.ACTION_VIEW, target);\n      legacy.setClassName(QUEST_BROWSER, QUEST_BROWSER + ".WebVRActivity");\n      try { startActivity(legacy); } catch (ActivityNotFoundException ignored) {}\n    } finally { finish(); }\n  }\n\n  private Uri validatedTarget(Uri data) {\n    String raw = data == null ? null : data.getQueryParameter("url");\n    Uri target;\n    try { target = Uri.parse(raw == null || raw.isEmpty() ? DEFAULT_URL : raw); } catch (Exception e) { return null; }\n    if (!"https".equalsIgnoreCase(target.getScheme())) return null;\n    if (!"rantlist.me".equalsIgnoreCase(target.getHost())) return null;\n    String path = target.getPath();\n    if (path == null || !(path.equals("/stage") || path.startsWith("/stage/"))) return null;\n    return target;\n  }\n}\n`);
console.log('Quest XR bridge injected.');
