#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const root=path.resolve(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,n),'utf8');
let n=0;function check(x,f){f();n++;console.log('PASS '+x)}
const pkg=read('PACKAGE_VERSION.txt').trim(),gradle=read('mobile/quest/app/build.gradle'),manifest=read('mobile/quest/app/src/main/AndroidManifest.xml'),build=read('scripts/build_quest_release.sh');
check('Quest launch/install hotfix package is 0.1.299 or later',()=>{const p=pkg.split('.').map(Number);assert(p.length===3&&p.every(Number.isInteger));assert(p[0]>0||p[1]>1||(p[1]===1&&p[2]>=299))});
check('Quest uses Android Browser Helper artifact that supplies declared LauncherActivity',()=>{assert(gradle.includes("com.google.androidbrowserhelper:androidbrowserhelper:2.5.0"));assert(!gradle.includes('com.meta.androidbrowserhelper:androidbrowserhelper:2.5.0'));assert(manifest.includes('com.google.androidbrowserhelper.trusted.LauncherActivity'))});
check('Quest build validates LauncherActivity without pipefail/grep-q false failures',()=>{assert(build.includes("unzip -Z1 \"$APK_SRC\""));assert(build.includes('launcher_descriptor'));assert(build.includes('grep -F \"$launcher_descriptor\" >/dev/null'));assert(!build.includes("grep -Fq 'Lcom/google/androidbrowserhelper/trusted/LauncherActivity;'"));assert(build.includes('refusing to publish a non-launchable APK'))});
check('Quest release automatically installs and launches on a connected authorised Quest',()=>{assert(build.includes('RANTLIST_QUEST_INSTALL_CONNECTED:-1'));assert(build.includes('install_connected_quest_devices'));assert(build.includes('install -r "$APK"'));assert(build.includes('shell monkey -p fun.workwork.rantlist -c android.intent.category.LAUNCHER 1'));assert(build.includes('No connected/authorised Meta Quest found'));});
check('Quest install function declaration is executable, not escaped text',()=>{assert(!build.includes('\\ninstall_connected_quest_devices() {'));const start=build.indexOf('install_connected_quest_devices() {'),end=build.indexOf('\n[[ "$(uname -s)" == Darwin ]]');assert(start>=0&&end>start);const fn=build.slice(start,end);const r=cp.spawnSync('bash',['-c',`set -Eeuo pipefail\nlog(){ :; }\n${fn}\nINSTALL_CONNECTED=0\ninstall_connected_quest_devices\n`],{encoding:'utf8'});assert.strictEqual(r.status,0,`Quest install function failed to execute: ${r.stderr||r.stdout}`)});
check('Quest remains 2D TWA so in-page requestSession can enter WebXR',()=>{assert(manifest.includes('horizonos.pwa.APP_MODE'));assert(manifest.includes('android:value="2D"'));assert(manifest.includes('com.oculus.intent.category.2D'))});
console.log(`Client Quest launch regression r544: ${n} checks passed.`);
