#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');const read=n=>fs.readFileSync(path.join(root,n),'utf8');let n=0;
function check(name,fn){fn();n++;console.log('PASS '+name);}
const pkg=read('PACKAGE_VERSION.txt').trim(),source=JSON.parse(read('web/client-source.json'));
const phoneManifest=read('mobile/android/app/src/main/AndroidManifest.xml');
const template=JSON.parse(read('mobile/quest/twa-manifest.template.json'));
const build=read('scripts/build_quest_release.sh'),writer=read('scripts/write_quest_twa_manifest.js');
const release=read('scripts/release_and_deploy_homepage.sh'),github=read('scripts/publish_github_release.sh'),home=read('scripts/deploy_homepage.sh');
check('client r537 metadata is current',()=>{const p=pkg.split('.').map(Number),s=source.sourceVersion.split('.').map(Number),r=Number(String(source.sourceRevision).match(/r(\d+)$/)?.[1]);assert.ok(p[2]>=287);assert.ok(s[2]>=510);assert.ok(r>=538);});
check('Android phone APK no longer carries Quest-only launcher metadata',()=>{assert(!phoneManifest.includes('com.oculus.supportedDevices'));assert(!phoneManifest.includes('com.oculus.intent.category.2D'));assert(phoneManifest.includes('android.intent.action.SEND'));});
check('Quest source is a Bubblewrap manifest rather than a hand-written Gradle wrapper',()=>{assert.equal(template.packageId,'fun.workwork.rantlist');assert.equal(template.isMetaQuest,true);assert.equal(template.horizonOSAppMode,'2D');assert.equal(template.webManifestUrl,'https://rantlist.me/manifest.webmanifest');assert.equal(template.shareTarget.action,'https://rantlist.me/pwa-share-target');assert.ok(template.shareTarget.params.files.length);assert(!fs.existsSync(path.join(root,'mobile/quest/app/build.gradle')));});
check('Quest build pins the published Meta Bubblewrap CLI',()=>{assert(build.includes('@meta-quest/bubblewrap-cli'));assert(build.includes('1.24.1'));assert(build.includes('bubblewrap'));assert(build.includes('update --skipVersionUpgrade'));assert(build.includes('app-release-signed.apk'));assert(build.includes('app-release-bundle.aab'));});
check('Quest Bubblewrap build uses isolated generated output and existing signing identity',()=>{assert(build.includes('.quest-bubblewrap-build/project'));assert(build.includes('BUBBLEWRAP_KEYSTORE_PASSWORD'));assert(build.includes('--signingKeyPath'));assert(writer.includes("manifest.horizonOSAppMode='2D'"));});
check('Quest Bubblewrap first-run tool configuration is non-interactive and uses one accepted SDK root',()=>{assert(build.includes('BUBBLEWRAP_CONFIG_DIR="$HOME/.bubblewrap"'));assert(build.includes('config.json'));assert(build.includes('JDK_BUNDLE'));assert(build.includes('find_sdkmanager'));assert(build.includes('BUBBLEWRAP_SDK="$ROOT/.quest-bubblewrap-build/android-sdk"'));assert(build.includes('ln -sfn "$SDKMANAGER_DIR" "$BUBBLEWRAP_SDK/bin"'));assert(build.includes('unset ANDROID_SDK_ROOT'));assert(build.includes('export ANDROID_HOME="$BUBBLEWRAP_SDK"'));assert(build.includes('node - "$BUBBLEWRAP_CONFIG" "$JDK_BUNDLE" "$BUBBLEWRAP_SDK"'));assert(build.includes('"${BUBBLEWRAP[@]}" doctor'));assert(!build.includes('export ANDROID_HOME="$SDK_ROOT"'));assert(build.indexOf('fs.writeFileSync(configPath')<build.indexOf('"${BUBBLEWRAP[@]}" --version'));});
check('release publishing still includes separate Android and Quest artifacts',()=>{assert(release.includes('build_android_release.sh'));assert(release.includes('build_quest_release.sh'));assert(github.includes('${BASE}-android.apk'));assert(github.includes('${BASE}-quest.apk'));assert(home.includes("button('android_apk','Android APK'"));assert(home.includes("button('quest_apk','Meta Quest APK'"));});
check('source whitespace verifier excludes generated Quest builds',()=>{const ws=read('scripts/verify_source_whitespace.js');assert(ws.includes("'.quest-bubblewrap-build'"));assert(ws.includes("'build'"));assert(ws.includes("'.gradle'"));});
console.log(`Client Meta Quest Bubblewrap r537: ${n} regression groups passed.`);
